name: Deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: sander102907
          password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      
      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: frontend/
          push: true
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          tags: |
            ghcr.io/sander102907/frontend-recipes-app:latest

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: backend/
          push: true
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          tags: |
            ghcr.io/sander102907/backend-recipes-app:latest
