name: Test Application

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened, synchronize]

jobs:
  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
      with:
        working-directory: ./frontend
        package-manager: yarn
        test-script: yarn test --silent --coverage --coverageReporters="text" --coverageReporters="text-summary"
        #threshold: 80
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
      with:
        working-directory: ./backend
        package-manager: npm
        test-script: npm test --silent --coverage --coverageReporters="text" --coverageReporters="text-summary"
        #threshold: 80
    
