name: Test Application on Pull Request

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened, synchronize]

jobs:
  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install dependencies
      working-directory: ./frontend
      run: yarn ci
    - name: Run tests
      working-directory: ./frontend
      run: yarn test
    - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
      with:
        github-token: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      run: npm run build --if-present
    - name: Run tests
      working-directory: ./backend
      run: npm run test
    - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
      with:
        github-token: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
    
